### ISSUE TITLE
Question format

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#1]
We need to decide whether we want all questions to have the same three buttons: "A", "B", and "ask someone else" or if we want the buttons to reflect the question-specific answers, e.g. "Paraguay", "Honduras", "Ask Someone Else." This will determine how we record their answers and decide if it's correct or not.
Is it simpler to have everything be "A" and "B" and then have a list somewhere linking which questions "A" is correct for and which questions "B" is correct for? 
Similarly, can we have some questions which display a photo as part of the question? For Qualtrics 5/25 questions were photo questions for each topic, just to make it less dull for participants and more motivating.

**Comment by thomasmorgan** [comment]
If questions are infos transmitted by a source node the easiest way to do this is to have the contents of the info be a JSON structure that defines the question, answers, and right answer. The front end can then use this info to update its display. Here's an example:

```
contents = {
"question": "What is the capital of France?",
"A": "Paris",
"B": "Toulouse",
"correct answer": "Paris"
}
```

Displaying an image is fine too. You would just add an extra field to the JSON that specified the url of the image.
