### ISSUE TITLE
Question timer

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#11]
So the latest issue with the timer is when we get to the Round 2 div. 

A) If it takes the person longer than 15 seconds to press "okay I understand" then everything goes blank and breaks. Even though I thought I had cleared the answer_timeout for this part (line 101 in experiment.js) 

B) if some of them click the right/wrong answer at different times after the round 2 check, their timers start at different times and don't countdown for the first question in round 2. 

C) the timers are displayed during "ask someone else" in Round 2 (even though they aren't in Round 1?) 

I will ask Alex if he thinks it's necessary to actually have a visible timer, (I like the idea as I think it'll put the pressure on people to only answer if they're sure, otherwise ask someone else, and also to remind them they don't have time to Google answers..!) But, if the visibility of the timer at various parts ends up being too messy, maybe we just keep the page timeout without the visibility and tell them it will move them on. (Ideally at least a message saying "time's up!" or something would come up when/if they don't answer in time). 

Let me know if this is easily achievable and just needs tweaking, or if we should consider abandoning a visible timer at all.

**Comment by thomasmorgan** [comment]
I think the generic message is fine, you might just want to let people know in the instructions that others might choose to copy and this can slow things down. But you can put the copiers on a 10 second timer too, so it shouldn't take too long.

For more on timers see the setTimeout() function: https://www.w3schools.com/jsref/met_win_settimeout.asp

**Comment by lottybrand** [comment]
A small addition: 
I've added lots of "clearTimeout(answer_timeout);" everywhere, but it still seems to timeout during round2div if no one clicks "okay I understand", 
The only other thing is that during div2check, if a player presses the wrong answer first, so that "WRONG ANSWER PLEASE READ AGAIN" displays, then even if everyone selects the correct answer, the div2check info will be displayed below the following question..... if you see what I mean.

**Comment by lottybrand** [comment]
(and the timer for the first question in round 2 freezes, but the rest of the questions in round 2 are fine).
