### ISSUE TITLE
Select copied answer and move on

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#15]
Once the player has selected "A3" to copy, we need the game to move on to the next question for everyone. (And when we calculate scoring we need to assign the copier the same score as who they copied, for that question).

**Comment by thomasmorgan** [comment]
Yes, this is pretty much already in place. If you look at the `info_post_request` function in experiment.py (which runs whenever anyone creates an info) it checks to see if everyone has answered and if they have it moves everyone on to the next question:

```
            if not "Ask Someone Else" in answers:
                #if no one has copied then get the source to transmit to all of its neighbors
                source = node.neighbors(type=Source, direction="from")[0]
                source.transmit()
                nodes = source.neighbors()
```
so what you need is for the copier to save their copied decision and the rest should just happen
