### ISSUE TITLE
Conditions and Rounds structuring

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#17]
What we have at the moment is essentially Condition A, Round 1. 
For Conditions B and C, we will be displaying the score as buttons instead of the player ID. 

For Round 2 in all conditions, we want there to be an "extra step" in which participants choose whether they want to view player_ID or number_of_times_copied(Condition A), before they see this information.

**Comment by thomasmorgan** [comment]
I don't follow, can you try to unpack this a bit? Otherwise we can talk about it tomorrow.

**Comment by lottybrand** [comment]
Yep probably easier to discuss over Skype and in the meantime I'll play around with the scoring stuff and adding in more questions
