### ISSUE TITLE
picture questions

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#19]
Just remembered that ideally we want a few of the questions from each topic to have pictures, to match our qualtrics design (this is just to make the quiz a bit more fun/interesting, to make the art topic more appropriate, and to help those who are less "wordy") ...
is there a simple way of adding a picture argument to some of the models.py questions (like Round and number)... and then I guess the javascript will have a "if picture == yes, display picture" type thing?

**Comment by lottybrand** [comment]
For this would I save all the images in a folder, say the 'images' folder, as there currently seems to be one. Then, in the JSON object could I add an argument for image: Y/N. and then if it is image= Y then it displays the image from the folder with the question? Would this be the simplest way as there will be images for some questions but not others?

**Comment by thomasmorgan** [comment]
Yes, that sounds sensible. See here for an intro to inserting images into html pages: https://www.w3schools.com/tags/tag_img.asp
