### ISSUE TITLE
Assign and display unique IDs for participants in each team

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#2]
I'm guessing worker_ID and assignment_ID are long complicated number/letter combos? We don't really want participants to have to see that, a neat "A1, A2, A3" type thing for everyone in "team A" would be neat. So we need to create some infos? And display those to each participant at the beginning once they'e read the instructions and consented.

**Comment by thomasmorgan** [comment]
There's no need to create infos for this as nodes already have numeric node ids which we can use.

Assumption: each group consists of a single network containing a number of nodes joined by vectors.

When participants join they will be assigned a node. They can check their nodes network_id (numeric starting from 1, I think) and use this to create a group label (e.g. network_id 1 = group "A", 2 = group "B" and so on)

They will also know their node id (again, numeric), this can be appended to give them their unique ID, e.g. node 12 in network 3 will be player "C12".

One problem with this is that node ids are unique across all networks, and so there can only be one node 1 across all networks, this means you might be playing with players "A1", "A5", and "A17" which doesn't make a lot of sense. To adjust this requires a bit more work:

You can request a description of all your neighbors from the /neighbors route (neighbors are nodes you are connected to). From this you can get a list of all the node ids of your neighbors. You can add your own id to this list to get a list of the node ids of everyone in your group. You can then just order this and have the node with the lowest node id be node 1 in your group, and so on. This would turn players "A1", "A5", and "A17" into A1 A2 and A3.

What do you think?

**Comment by lottybrand** [comment]
I'm assuming my code at the moment doesn't work as we are debugging in debug mode and not sandbox, so no "network" or "network ids" as such exist...? or am I wrong?
