### ISSUE TITLE
drop out in Round 2

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#25]
I've now tested this twice and I'm pretty confident that I know when this error occurs, but I'm not entirely sure why. 
Essentially, in Round 2, if someone chooses 'ask someone else' and others close their windows before answering, then everyone is held at 'waiting for others to catch up' while the n_requests get to 60. Then everyone except a couple of players are sent to an error page, and one of the 'ask someone else' players is then shown the info_choices, and is able to carry on playing with the one remaining player. See screenshots below. 
More details to be sent over email. 
This has happened twice in the exact same way each time.

**Comment by lottybrand22** [comment]
![screenshot1 2019-02-12 at 16 20 02](https://user-images.githubusercontent.com/18070643/52651739-a0ff0700-2ee4-11e9-928e-e363ddc87168.png)
![screenshot2 2019-02-12 at 16 20 26](https://user-images.githubusercontent.com/18070643/52651741-a0ff0700-2ee4-11e9-96bd-8330c4eb4009.png)
![screenshot3 2019-02-12 at 16 20 53](https://user-images.githubusercontent.com/18070643/52651743-a0ff0700-2ee4-11e9-89da-cfc7fb388b57.png)
![screenshot4 2019-02-12 at 16 21 11](https://user-images.githubusercontent.com/18070643/52651744-a0ff0700-2ee4-11e9-8ed2-27956cea1cb4.png)

**Comment by lottybrand22** [comment]
I have just tested it again in Round 1, and it seems that in Round 1, whether the drop-out closes their window before or after they've selected an answer, the other players just have to wait for the 60 seconds max before being moved on to the next question. For some reason in Round 2, it appears that the counter can keep going beyond 60 and get stuck for a very long time until it pushes people on to the next question? I really have no idea why... unless it's just a coincidence that I've only been able to repeat the error in Round 2...???

**Comment by lottybrand** [comment]
![ase_r2_1_screen shot 2019-02-18 at 13 48 09](https://user-images.githubusercontent.com/18070643/52958749-a3ea7380-338c-11e9-9315-395fc3ba33fc.png)
![ase_r2_2_screen shot 2019-02-18 at 13 48 54](https://user-images.githubusercontent.com/18070643/52958750-a4830a00-338c-11e9-8db1-643b851c3c64.png)
![ase_r2_3_screen shot 2019-02-18 at 13 49 11](https://user-images.githubusercontent.com/18070643/52958751-a4830a00-338c-11e9-9275-51607d71f0d5.png)
![ase_r2_4_screen shot 2019-02-18 at 13 50 39](https://user-images.githubusercontent.com/18070643/52958752-a4830a00-338c-11e9-8f07-a64f7817f01c.png)
