### ISSUE TITLE
Recording participants' answers

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#3]
We need to save each button click of the participant. I guess this is already automatically saved but we then need to show all those that clicked "ask someone else" a list of IDs of those who didn't click "ask someone else" 
I'm assuming this is about transmitting infos again.

**Comment by thomasmorgan** [comment]
This is mostly about handling communication between the server and client, though there will be some new infos being created and possibly some transmission too. This should be conceptually quite straight forward though can be a hassle to implement.

Probably the easiest way to start is to have the button clicks send a request back to the server to save the participant's/node's decision (the /info POST route does this), once this is successful the "button clicked" function can then send participants on to different pages/functions depending on which button was clicked.

If they made a final decision they will repeatedly ping the server waiting for the next question which will only be made available once everyone has decided (the server will need to check for this, questions will be sent as a transmission, probably from a source node).

If they chose to copy, they will repeatedly ping the server waiting for everyone to decide whether to copy or not (the server will need to check for this too). Once this is done they will need to ask for the decisions of everyone who made a decision (sent as transmissions between nodes), and they can display these decisions to the participant.

Make sense?
