### ISSUE TITLE
"finish reading"

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#4]
" #finish reading " seems to appear a lot as it's leftover from the Bartlett set-up. I don't think we need this still but it seems to be a crucial part of some files, is it a matter of re-naming it? I'm not sure I know what it's function is at the minute. I feel like I could delete it from experiment.js but then I feel like it will have a knock-on effect for experiment.py (e.g. line 93?).

**Comment by thomasmorgan** [comment]
#finish-reading was the id of a button that was part of the original bartlett1932 interface (you clicked it to say you had finished reading the story). However, you removed this button from the interface in commit [8a650089e7fbd15b6eb7f5dec692e364e6f36079](https://github.com/lottybrand22/lottysBartlett/commit/8a650089e7fbd15b6eb7f5dec692e364e6f36079). Given this, all of the code that references this button in experiment.js is very likely non functional and so can be removed without harm.
