### ISSUE TITLE
Display ppt characteristics as choices

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#8]
At the moment we can show non-copier id's as buttons to choose from. We want to also show other information such as how many times they have been copied, or their score so far on the quiz. So perhaps instead of having all of this information on the button, we will have a table/screen of info about each non-copier be displayed, with a button underneath to choose from

**Comment by lottybrand22** [comment]
Currently I can get the first neighbor's id to print in the console, and a button to appear, but not the id on the button. Also cannot retrieve "player_id" only, "id"

**Comment by lottybrand22** [comment]
At the moment I can get one of the participant_id (not player_id) of a non-copier to display to the copier as a button, if the player clicks the button it is logged to the database as "copied"

**Comment by lottybrand22** [comment]
At the moment we are trying to show neighbor id's as buttons to choose from. Eventually we will also be showing other information such as how many times they have been copied, or their score so far on the quiz. So perhaps instead of having all of this information on the button, we will have a table/screen of info about each non-copier be displayed, with a button underneath to choose from. (Although, admittedly, I guess that button would usefully be labelled with player_id anyway... so we still do need to do that too!)

**Comment by thomasmorgan** [comment]
yep, you should look up how to construct tables in html: https://www.w3schools.com/html/html_tables.asp

Also, the easiest way to do this is to have each node use the property columns to store their score and number of times copied, then you can read straight from the node objects to fill out the table.

**Comment by lottybrand** [comment]
For now, to keep consistent with the previous experiments and plan, I'd like to stick with buttons, and just have an extra choice after each "ask someone else" whether they see player_id or number_times_copied.  I like the table idea for another iteration that I'd like to try after this version (and depending on how piloting goes) to investigate "runaway effects" too.

**Comment by thomasmorgan** [comment]
Ah ok, got it. Even so you might want to use a table to control how information is presented. Let's assume someone chooses to view the number of times someone was copied. Will they see something like this:

\---------------------------------
\|    A1     |        A2      |        A3       |
\---------------------------------
\|     4     |        13       |         3        |
\---------------------------------

Where A1/A2 and A3 will be buttons?

edit: sorry, github markdown is messing up my pseudo table above, but hopefully you get the idea.
