### ISSUE TITLE
turning things off

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#9]
Need to make buttons /messages appear/ disappear at the appropriate times. Currently the answer buttons are on the welcome page unnecessarily, and they remain there throughout the "badluck" message, and the "badluck" message never goes away. Similarly the "goodluck"  message stays, as does the copier button, but the questions carry on moving through. This must be some simple html rearranging stuff

**Comment by thomasmorgan** [comment]
Its not so much html as it is javascript. The html lists everything on the page, but to show/hide things, or to change the text in a header/paragraph you need to use javascript.

see:
https://www.w3schools.com/jquery/jquery_hide_show.asp
